name: My-GitHub-Actions
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches: 
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in testing
        run : echo "Hello world from testing"
        
      - name: Execute few commands
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run: la -la
        
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Print Hello Message in deploy
        run: echo "Hello message from deploy"
        
      - name: Printing Deploy message
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
        
