name: My-GitHub-Actions
on:
  push:
    branches: 
      - master
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run : echo "Hello world from testing"
        
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello message from deploy"
        
